// =====================================================================
// RS_GH_ magazines -- one chambered-ammo class per weapon per identity,
// same convention as the main arsenal (AmmoType2 = rounds in the gun).
// Capacities taken from the source pack's own HF_HB_*Mag classes.
// =====================================================================
class RS_GH_PistolLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 16; Ammo.BackpackMaxAmount 16; +INVENTORY.IGNORESKILL } }
class RS_GH_PistolLoaded2 : RS_GH_PistolLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 16; Ammo.BackpackMaxAmount 16; +INVENTORY.IGNORESKILL } }
class RS_GH_PistolLoaded3 : RS_GH_PistolLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 16; Ammo.BackpackMaxAmount 16; +INVENTORY.IGNORESKILL } }
class RS_GH_PistolLoaded4 : RS_GH_PistolLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 16; Ammo.BackpackMaxAmount 16; +INVENTORY.IGNORESKILL } }
class RS_GH_PistolLoaded5 : RS_GH_PistolLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 16; Ammo.BackpackMaxAmount 16; +INVENTORY.IGNORESKILL } }
class RS_GH_PistolLoaded6 : RS_GH_PistolLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 16; Ammo.BackpackMaxAmount 16; +INVENTORY.IGNORESKILL } }
class RS_GH_RevolverLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RevolverLoaded2 : RS_GH_RevolverLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RevolverLoaded3 : RS_GH_RevolverLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RevolverLoaded4 : RS_GH_RevolverLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RevolverLoaded5 : RS_GH_RevolverLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RevolverLoaded6 : RS_GH_RevolverLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_PumpShotgunLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 9; Ammo.BackpackMaxAmount 9; +INVENTORY.IGNORESKILL } }
class RS_GH_PumpShotgunLoaded2 : RS_GH_PumpShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 9; Ammo.BackpackMaxAmount 9; +INVENTORY.IGNORESKILL } }
class RS_GH_PumpShotgunLoaded3 : RS_GH_PumpShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 9; Ammo.BackpackMaxAmount 9; +INVENTORY.IGNORESKILL } }
class RS_GH_PumpShotgunLoaded4 : RS_GH_PumpShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 9; Ammo.BackpackMaxAmount 9; +INVENTORY.IGNORESKILL } }
class RS_GH_PumpShotgunLoaded5 : RS_GH_PumpShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 9; Ammo.BackpackMaxAmount 9; +INVENTORY.IGNORESKILL } }
class RS_GH_PumpShotgunLoaded6 : RS_GH_PumpShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 9; Ammo.BackpackMaxAmount 9; +INVENTORY.IGNORESKILL } }
class RS_GH_AssaultShotgunLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 20; Ammo.BackpackMaxAmount 20; +INVENTORY.IGNORESKILL } }
class RS_GH_AssaultShotgunLoaded2 : RS_GH_AssaultShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 20; Ammo.BackpackMaxAmount 20; +INVENTORY.IGNORESKILL } }
class RS_GH_AssaultShotgunLoaded3 : RS_GH_AssaultShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 20; Ammo.BackpackMaxAmount 20; +INVENTORY.IGNORESKILL } }
class RS_GH_AssaultShotgunLoaded4 : RS_GH_AssaultShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 20; Ammo.BackpackMaxAmount 20; +INVENTORY.IGNORESKILL } }
class RS_GH_AssaultShotgunLoaded5 : RS_GH_AssaultShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 20; Ammo.BackpackMaxAmount 20; +INVENTORY.IGNORESKILL } }
class RS_GH_AssaultShotgunLoaded6 : RS_GH_AssaultShotgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 20; Ammo.BackpackMaxAmount 20; +INVENTORY.IGNORESKILL } }
class RS_GH_SSGLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 2; Ammo.BackpackMaxAmount 2; +INVENTORY.IGNORESKILL } }
class RS_GH_SSGLoaded2 : RS_GH_SSGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 2; Ammo.BackpackMaxAmount 2; +INVENTORY.IGNORESKILL } }
class RS_GH_SSGLoaded3 : RS_GH_SSGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 2; Ammo.BackpackMaxAmount 2; +INVENTORY.IGNORESKILL } }
class RS_GH_SSGLoaded4 : RS_GH_SSGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 2; Ammo.BackpackMaxAmount 2; +INVENTORY.IGNORESKILL } }
class RS_GH_SSGLoaded5 : RS_GH_SSGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 2; Ammo.BackpackMaxAmount 2; +INVENTORY.IGNORESKILL } }
class RS_GH_SSGLoaded6 : RS_GH_SSGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 2; Ammo.BackpackMaxAmount 2; +INVENTORY.IGNORESKILL } }
class RS_GH_RifleLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 31; Ammo.BackpackMaxAmount 31; +INVENTORY.IGNORESKILL } }
class RS_GH_RifleLoaded2 : RS_GH_RifleLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 31; Ammo.BackpackMaxAmount 31; +INVENTORY.IGNORESKILL } }
class RS_GH_RifleLoaded3 : RS_GH_RifleLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 31; Ammo.BackpackMaxAmount 31; +INVENTORY.IGNORESKILL } }
class RS_GH_RifleLoaded4 : RS_GH_RifleLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 31; Ammo.BackpackMaxAmount 31; +INVENTORY.IGNORESKILL } }
class RS_GH_RifleLoaded5 : RS_GH_RifleLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 31; Ammo.BackpackMaxAmount 31; +INVENTORY.IGNORESKILL } }
class RS_GH_RifleLoaded6 : RS_GH_RifleLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 31; Ammo.BackpackMaxAmount 31; +INVENTORY.IGNORESKILL } }
class RS_GH_SMGLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 41; Ammo.BackpackMaxAmount 41; +INVENTORY.IGNORESKILL } }
class RS_GH_SMGLoaded2 : RS_GH_SMGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 41; Ammo.BackpackMaxAmount 41; +INVENTORY.IGNORESKILL } }
class RS_GH_SMGLoaded3 : RS_GH_SMGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 41; Ammo.BackpackMaxAmount 41; +INVENTORY.IGNORESKILL } }
class RS_GH_SMGLoaded4 : RS_GH_SMGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 41; Ammo.BackpackMaxAmount 41; +INVENTORY.IGNORESKILL } }
class RS_GH_SMGLoaded5 : RS_GH_SMGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 41; Ammo.BackpackMaxAmount 41; +INVENTORY.IGNORESKILL } }
class RS_GH_SMGLoaded6 : RS_GH_SMGLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 41; Ammo.BackpackMaxAmount 41; +INVENTORY.IGNORESKILL } }
class RS_GH_MP40Loaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 32; Ammo.BackpackMaxAmount 32; +INVENTORY.IGNORESKILL } }
class RS_GH_MP40Loaded2 : RS_GH_MP40Loaded { Default { Inventory.Amount 1; Inventory.MaxAmount 32; Ammo.BackpackMaxAmount 32; +INVENTORY.IGNORESKILL } }
class RS_GH_MP40Loaded3 : RS_GH_MP40Loaded { Default { Inventory.Amount 1; Inventory.MaxAmount 32; Ammo.BackpackMaxAmount 32; +INVENTORY.IGNORESKILL } }
class RS_GH_MP40Loaded4 : RS_GH_MP40Loaded { Default { Inventory.Amount 1; Inventory.MaxAmount 32; Ammo.BackpackMaxAmount 32; +INVENTORY.IGNORESKILL } }
class RS_GH_MP40Loaded5 : RS_GH_MP40Loaded { Default { Inventory.Amount 1; Inventory.MaxAmount 32; Ammo.BackpackMaxAmount 32; +INVENTORY.IGNORESKILL } }
class RS_GH_MP40Loaded6 : RS_GH_MP40Loaded { Default { Inventory.Amount 1; Inventory.MaxAmount 32; Ammo.BackpackMaxAmount 32; +INVENTORY.IGNORESKILL } }
class RS_GH_RocketLauncherLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RocketLauncherLoaded2 : RS_GH_RocketLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RocketLauncherLoaded3 : RS_GH_RocketLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RocketLauncherLoaded4 : RS_GH_RocketLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RocketLauncherLoaded5 : RS_GH_RocketLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_RocketLauncherLoaded6 : RS_GH_RocketLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 6; Ammo.BackpackMaxAmount 6; +INVENTORY.IGNORESKILL } }
class RS_GH_GrenadeLauncherLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 1; Ammo.BackpackMaxAmount 1; +INVENTORY.IGNORESKILL } }
class RS_GH_GrenadeLauncherLoaded2 : RS_GH_GrenadeLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 1; Ammo.BackpackMaxAmount 1; +INVENTORY.IGNORESKILL } }
class RS_GH_GrenadeLauncherLoaded3 : RS_GH_GrenadeLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 1; Ammo.BackpackMaxAmount 1; +INVENTORY.IGNORESKILL } }
class RS_GH_GrenadeLauncherLoaded4 : RS_GH_GrenadeLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 1; Ammo.BackpackMaxAmount 1; +INVENTORY.IGNORESKILL } }
class RS_GH_GrenadeLauncherLoaded5 : RS_GH_GrenadeLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 1; Ammo.BackpackMaxAmount 1; +INVENTORY.IGNORESKILL } }
class RS_GH_GrenadeLauncherLoaded6 : RS_GH_GrenadeLauncherLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 1; Ammo.BackpackMaxAmount 1; +INVENTORY.IGNORESKILL } }
class RS_GH_PlasmaLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_PlasmaLoaded2 : RS_GH_PlasmaLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_PlasmaLoaded3 : RS_GH_PlasmaLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_PlasmaLoaded4 : RS_GH_PlasmaLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_PlasmaLoaded5 : RS_GH_PlasmaLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_PlasmaLoaded6 : RS_GH_PlasmaLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_RailgunLoaded : Ammo { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_RailgunLoaded2 : RS_GH_RailgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_RailgunLoaded3 : RS_GH_RailgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_RailgunLoaded4 : RS_GH_RailgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_RailgunLoaded5 : RS_GH_RailgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
class RS_GH_RailgunLoaded6 : RS_GH_RailgunLoaded { Default { Inventory.Amount 1; Inventory.MaxAmount 50; Ammo.BackpackMaxAmount 50; +INVENTORY.IGNORESKILL } }
